### ISSUE TITLE
needs license terms

### ISSUE THREAD

**Issue by apotheon** [bekkopen/jasmineio#14]
Is this meant to be open source software?  Should we use it under the terms of the MIT/X11 License (same as Jasmine for JavaScript) or those of the Revised BSD License (same as Io itself)?  Please add a license file to let prospective users know what legal restrictions may apply.

**Comment by follesoe** [comment]
Went with the Revisited BSD (same as Io). Thanks for pointing out. Cool to see the new Io lang page! Should try to jasmineio listed as a library on the page.
